proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=STATIC:10m inactive=7d use_temp_path=off;

upstream nextjs_sql_chat_upstream {
    server localhost:4001;
}

server {
    etag off;
    client_body_buffer_size 100M;
    client_max_body_size 100M;
    proxy_send_timeout 60s;
    proxy_read_timeout  30s;

    server_tokens off;

    gzip on;
    gzip_proxied any;
    gzip_comp_level 4;
    gzip_types text/css application/javascript image/svg+xml;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;

    server_name sql-chat.thape.com.cn;
    root /var/www/sql_chat/current/public;

    location /_next/static {
        proxy_cache STATIC;
        proxy_pass http://nextjs_sql_chat_upstream;
        access_log /var/www/sql_chat/shared/log/nextjs_static.access.log;
        error_log /var/www/sql_chat/shared/log/nextjs_static.error.log;
    }

    location /public {
        proxy_cache STATIC;
        proxy_ignore_headers Cache-Control;
        proxy_cache_valid 60m;
        proxy_pass http://nextjs_sql_chat_upstream;
        access_log /var/www/sql_chat/shared/log/nextjs_public.access.log;
        error_log /var/www/sql_chat/shared/log/nextjs_public.error.log;
    }

    location / {
        proxy_pass http://nextjs_sql_chat_upstream;
        access_log /var/www/sql_chat/shared/log/nextjs_root.access.log;
        error_log /var/www/sql_chat/shared/log/nextjs_root.error.log;
    }

    listen 443 ssl;
    ssl_certificate /etc/ssl/cert/STAR_thape_com_cn_integrated.crt;
    ssl_certificate_key /etc/ssl/private/STAR_thape_com_cn.key;
}

server {
    if ($host = sql-chat.thape.com.cn) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name sql-chat.thape.com.cn;
    return 404;
}
